# Generated by Django 3.2.4 on 2021-12-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_apply_related',
            field=models.BooleanField(default=False),
        ),
    ]
