# Generated by Django 3.2.4 on 2021-12-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_modules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created']},
        ),
    ]
