# Generated by Django 3.2.4 on 2021-12-29 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_message'),
        ('projects', '0006_rename_is_fulled_group_is_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_apply',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
