# Generated by Django 3.2.4 on 2021-12-30 02:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20211229_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='feature',
            field=models.CharField(choices=[('delicacy', '美食評鑑'), ('finance', '投資理財'), ('sport', '運動健身'), ('pet', '寵物生活'), ('toolkit', '輔助工具'), ('society', '社會政治'), ('shopping', '購物達人'), ('entertainment', '音樂電影'), ('other', '其他')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='projects.Type'),
        ),
    ]
