# Generated by Django 3.2.4 on 2021-12-30 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20211230_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='types',
        ),
    ]
