# Generated by Django 3.2.4 on 2021-12-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211222_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='modules',
            field=models.ManyToManyField(blank=True, null=True, to='projects.Module'),
        ),
    ]
