# Generated by Django 3.2.4 on 2021-12-30 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message_is_apply_related'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read', '-is_apply_related', '-created']},
        ),
    ]
